# Generated by Django 5.2.10 on 2026-02-13 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_move_endpoint_from_endpoints_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.app')),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('app', 'slug'), name='unique_environment_slug_per_app')],
            },
        ),
    ]
